# -*- coding: utf-8 -*-
"""Copy of Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z92yuxBZyw7yMxHcjFG3_z0vGgzWKvU-
"""

!pip install transformers gradio

import gradio as gr
from transformers import pipeline
import random

caption_generator = pipeline("text-generation", model="gpt2")

emoji_dict = {
    "positive": [
        "🙂", "😊", "🌟", "🔥", "💪", "🚀", "✨"
    ],
    "negative": [
        "😢", "😞", "💔", "😠", "😓"
    ],
    "neutral": [
        "😐", "🧐", "🤔", "😶"
    ]
}

# Load sentiment analysis pipeline
sentiment_pipeline = pipeline("sentiment-analysis")

# Function to get emojis based on sentiment
def get_emojis(text):
    label = sentiment_pipeline(text)[0]['label'].lower()
    return ''.join(random.sample(emoji_dict.get(label, ["🙂"]), 3))

def get_hashtags(prompt, platform):
 words = prompt.lower().split()
 tags = ["#" + word.replace(" ", "") for word in words if len(word) > 3]
 platform_tags = {
 "Instagram": ["#instadaily", "#igers", "#picoftheday"],
 "LinkedIn": ["#career", "#leadership", "#networking"],
 "Twitter": ["#tweet", "#trending", "#news"]
 }
 return " ".join(tags[:5] + random.sample(platform_tags[platform], 2))

def generate_post(prompt, platform):
    try:
        prompt_text = f"Write a short, catchy {platform} caption about: {prompt}"
        result = caption_generator(prompt_text, max_length=20, num_return_sequences=1)[0]

        # Safely extract text
        caption = result.get('generated_text', '').strip()

        # Defensive checks
        if not caption:
            caption = "Could not generate caption."

        emojis = get_emojis(caption)
        hashtags = get_hashtags(prompt, platform)

        return caption, emojis, hashtags

    except Exception as e:
        # Print error to console for debugging
        print("Error in generate_post:", e)
        import traceback
        traceback.print_exc()
        return f"Error: {e}", "Error", "Error"

interface = gr.Interface(
    fn=generate_post,
    inputs=[
        gr.Textbox(label="Enter keyword or theme"),
        gr.Radio(["Instagram", "LinkedIn", "Twitter"], label="Choose Platform")
    ],
    outputs=[
        gr.Textbox(label="Generated Caption"),
        gr.Textbox(label="Emojis"),
        gr.Textbox(label="Hashtags")
    ],
    title="Social Media Post & Caption Generator",
    description="Generate catchy captions, relevant emojis, and hashtags based on your keyword or theme."
)

interface.launch()

